version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: windows
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
    goamd64:
      - v1
      - v4
    ldflags:
      - -s -w

  - id: linux
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - 386
      - amd64
      - arm
      - arm64
      - riscv64
    go386:
      - sse2
    goamd64:
      - v1
      - v4
    goarm:
      - 5
      - 6
      - 7
    goarm64:
      - v8.0
    goriscv64:
      - rva20u64
    ldflags:
      - -s -w

archives:
  - id: default
    builds:
      - windows
      - linux
    wrap_in_directory: true
    formats: tar.gz
    format_overrides:
      - goos: windows
        formats: zip
    files:
      - LICENSE
      - README.md
      - config/**/*
      - systemd/*

snapshot:
  version_template: '{{ incpatch .Version }}-dev-{{.ShortCommit}}'

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"

release:
  prerelease: false
  draft: false

nfpms:
  - id: glider
    builds:
      - linux
    package_name: glider
    vendor: nadoo
    homepage: https://github.com/nadoo/glider
    maintainer: nadoo
    description: Glider is a forward proxy with multiple protocols support, and also a dns/dhcp server with ipset management features(like dnsmasq).
    license: GPL-3.0 License
    formats:
      - deb
    dependencies:
      - libsystemd0
    bindir: /usr/bin
    release: 1
    epoch: 1
    version_metadata: git
    section: default
    priority: extra
    contents:
      - src: systemd/glider@.service
        dst: /etc/systemd/system/glider@.service

      - src: config/glider.conf.example
        dst: /etc/glider/glider.conf.example

    scripts:
      postinstall: "systemd/postinstall.sh"
      preremove: "systemd/preremove.sh"
      postremove: "systemd/postremove.sh"

    deb:
      triggers:
        interest_noawait:
          - /lib/systemd/systemd
